### ISSUE TITLE
Dependency graph

### ISSUE THREAD

**Issue by pferrot** [autodesk-cloud/ochothon#14]
It would be nice if Ochothon could generate kind of dependency graph of the running pods, something similar to what build tools like Maven or SBT allow for library dependencies.

E.g. say I have a reverse proxy (my-reverse-proxy), which depends on 2 load balancers (lb-app-1 and lb-app-2). Those 2 load balancers depend on their respective applications: app-1 and app-2. Say you have two instances of app-1 and two instances of app-2. Then the graph could look like this:

```
my-reverse-proxy
+- lb-app-1
    +- app-1 (3)
+- lb-app-2
    +- app-2 (2)
```

I started looking into this the other day, a library like NetworkX could be leveraged and it would be fairly easy to do except that it seems Ochopod does not provide the pod dependencies when it is queried through the /info API. So that would need to be implemented.

Anyway, this is certainly a nice to have. But precisely: nice to have are...nice to have :-)

**Comment by opaugam** [comment]
Hey Patrice !

Mmh - this is a good question albeit quite complex to manage properly. What would you use that for if I may ask ?

If you are thinking about deployment (or rather recursive deployment) I'd personally prefer to take it under a slightly different angle -> be able to deploy a "subsystem" made of multiple pods.. this is what i'm currently setting up for our CD effort..

**Comment by pferrot** [comment]
Actually nothing that complicated. What I am looking for is just a way to _document_ my Ochopod clusters, i.e. simply draw a graph of what is currently running. I understand that this may not be something of real interest of Ochothon, so I very quickly created my own little tool for this: https://github.com/pferrot/ochograph

I guess that this issue can be closed then. Thanks anyway!

**Comment by opaugam** [comment]
ahah octograph ! I love it - let me check this out..
