### ISSUE TITLE
Allow external and container port to be specified 

### ISSUE THREAD

**Issue by stphung** [autodesk-cloud/ochothon#4]
Currently there are two options which are to:
- Choose the external and container port to be the same port using syntax such as "9000 *"
- Choose the container port using syntax such as "9000"

It would be nice to be able to choose both so that it is possible to specify the external port and the container port. This allows reuse of the image since those typically launch applications on a static port. The use case for us is to be able to run the same image on N statically defined ports.

**Comment by opaugam** [comment]
the master code just fixed your meek issue :)
