### ISSUE TITLE
Best way to pass settings to app environment

### ISSUE THREAD

**Issue by stphung** [autodesk-cloud/ochothon#6]
The recommended way to pass settings is to use `json.loads(os.environ['pod'])` and return it as the second argument from configure. However when trying this it appears that the values are not able to be loaded because they are unicode strings. I'm not sure if this is supposed to be possible, if not what's the best way to pass settings data to the application as environment variables? Thanks!
##### Settings:

```
settings:
  test: 1
  x: y
  foo: bar
```
##### Sample output:

```
  2015-06-04 22:44:57,400 - INFO - {u'test': 1, u'x': u'y', u'foo': u'bar'}
  2015-06-04 22:44:57,405 - WARNING - lifecycle (piped process) : failed to configure -> ..n2.7/subprocess.py (1327) -> TypeError (execve() arg 3 contains a non-string value), shutting down
  2015-06-04 22:44:57,405 - INFO - lifecycle (piped process) : finalizing pod
  2015-06-04 22:44:57,419 - WARNING - model (reactive) : configuration failed -> ..models/reactive.py (371) -> AssertionError (1+ pods failed to configure)
```

**Comment by stphung** [comment]
Figured out the issue, in the test case above it is because the "test" key has a value of 1 which is deserialized as an integer type. To handle this case if I want to pass numbers through the way I am doing this is by forcing a string by quoting the value.

```
settings:
  foo: bar
  test: "1"
  x: y
```

It would be awesome if this could be handled internally, seems like it would make sense since that is the only reasonable thing to do given a dict that is meant to be converted to environment variables.

**Comment by opaugam** [comment]
mh oh i see - so basically forcing everything to key/value pair when passing that dict at the end of configure() ?

**Comment by stphung** [comment]
Yeah! It would be ensuring that the types are converted to strings.  For instance when passing a setting like {"x": 1, "foo": 2.1} I actually mean that in the environment I want them available as x=1 and foo=2.1. When these are extracted as environment variables within an application they will be strings so I don' t think there is anything else you could possibly mean to do.

I think this is good because it makes the pod yml configuration file representative of what it is intended to be in terms of types. It would be weird for me to have to declare:

```
settings:
  x: "1.25"
```

Because if something else is trying to parse it then it would interpret that as a string when thats not really what it is. The alternative would be to have everyone have to do this conversion of {"x": 1.25} => {"x": "1.25"} before returning the dict in `configure`, everyone would probably run into the same problem I did.

**Comment by opaugam** [comment]
FYI - this is actually a ochopod issue

**Comment by opaugam** [comment]
fixed in ochopod !

**Comment by stphung** [comment]
Awesome thanks!
